Document: orbited
Title: Debian orbited Manual
Author: <insert document author here>
Abstract: This manual describes what orbited is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/orbited/orbited.sgml.gz

Format: postscript
Files: /usr/share/doc/orbited/orbited.ps.gz

Format: text
Files: /usr/share/doc/orbited/orbited.text.gz

Format: HTML
Index: /usr/share/doc/orbited/html/index.html
Files: /usr/share/doc/orbited/html/*.html
